79 gui integration
MSU-CS3250-DreamTeam/Database pull request #83
Opened 2020-11-04 20:19 UTC by kevvo15

GUI implementation for our database program. As of now it runs when main.main() is called. It still needs work on the Update operation and more functionality in reports. #79

2020-11-04 20:29 UTC, domschneider approved these changes
I think this is great progress on a simple gui. Good job Kevin.

2020-11-04 20:32 UTC, alexandersanford approved these changes
This GUI looks wonderful. Having the same functionality as our menu but with clickable buttons will definitely improve the end-user experience. Thanks for working on this!

2020-11-08 20:14 UTC, JonathanGrant92 requested changes

2020-11-08 20:14 UTC, JonathanGrant92 commented on pom.xml
> +        <plugins>
We can actually use 9 though. Go to line 113 and 114, where a different version of this artifact is stated, and modify accordingly. No need for a duplicate of the same plugin!

2020-11-08 20:49 UTC, JonathanGrant92 requested changes

2020-11-08 20:49 UTC, JonathanGrant92 commented on src/main/java/com/dreamteam/database/GUI.java
> +                System.exit(0);
Change to frame.dispose() and frame2.dispose() to release gui resources without forcing a shutdown of the program.

2020-11-08 22:24 UTC, JonathanGrant92 approved these changes

2020-11-09 02:03 UTC, Alejandro-Rojas approved these changes

2020-11-09 05:12 UTC, merged